baseURL = "https://trietmvo.com/"
locale = "en"
title = "Triet Vo"
theme = "nostyleplease"
disableKinds = ["section", "taxonomy", "term", "RSS"]

[outputs]
  home = ["HTML"]
  section = ["HTML"]

[params]
  description = "Writing about interesting technical stuff"
  favicon = ""

  [params.theme_config]
    appearance = "light"
    back_home_text = ".."
    date_format = "02 January 2006"
    isListGroupByDate = false
    isShowFooter = false
    show_description = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = true
    style = "rrt"
    tabWidth = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[deployment]
order = [".png$", ".jpg$", ".gif$"]

[[deployment.targets]]
URL = "s3://trietmvo.com?region=us-east-1"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
